name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    strategy:
      matrix:
        runner-os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm, macos-13]
    runs-on: ${{ matrix.runner-os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: '0.14.1'

    - name: Build binaries
      run: |
        for optimization in Debug ReleaseSafe ReleaseFast ReleaseSmall; do
          zig build -Doptimize=$optimization
          mv zig-out/bin/detect_changed_files zig-out/bin/detect_changed_files-$optimization
        done

    - name: Prepare release assets
      run: |
        mkdir -p release

        for optimization in Debug ReleaseSafe ReleaseFast ReleaseSmall; do
          BINARY_NAME="detect_changed_files-${{ github.ref_name }}-${{ matrix.runner-os }}-${optimization}"
          # Copy the binary for the current optimization level
          mv "zig-out/bin/detect_changed_files-${optimization}" "release/$BINARY_NAME"
        done

    - name: Upload build artifacts
      if: matrix.runner-os != 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.runner-os }}-${{ github.ref_name }}
        path: release/
        retention-days: 365
